MPUSettings:
  i2c_address: 0x68 # Hexadecimal 0x68 is decimal 104
  # The I2C address of the MPU-6050. Usually 0x68.
  # Run 'sudo i2cdetect -y 1' to find it if you're unsure - requires i2c-tools
  knock_threshold: 12.0 # Example, user will tune this
  # Threshold for knock detection. This is the minimum acceleration magnitude (m/s^2)
  # on any single axis to be considered a knock.
  # You'll need to experiment: start with something like 15-25 and adjust.
  # A gentle tap might be ~10-15, a firmer knock 20-30+.
  accelerometer_range: "RANGE_2_G"
  # Valid values: Range.RANGE_2_G, Range.RANGE_4_G, Range.RANGE_8_G, Range.RANGE_16_G
  # Default is RANGE_2_G which is usually fine for the knock detection used for framespot.

NetworkSettings:
  target_host: "xx.xx.xx.xx"
  target_port: 5000
  endpoint: "/toggle-like"

TimingSettings:
  # Time in seconds to wait after a detected knock before processing another.
  debounce_time_seconds: 5

GeneralSettings:
  # Set to true to log actions without sending POST requests.
  safe_mode: false